server {
    listen 80;
    server_name localhost;

    # FRONTEND
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri /index.html;
    }

    # =========================
    # USER SERVICE
    # =========================
    location /api/users/auth/login {
        proxy_pass http://user_service:8002/auth/login;
    }

    location /api/users/auth/register {
        proxy_pass http://user_service:8002/auth/register;
    }
    # =========================
    # LEARNING SERVICE
    # =========================
    location /api/learning/ {
        proxy_pass http://learning_service:8001/learning/;
    }



    # =========================
    # ATTEMPTS SERVICE
    # =========================
    location /api/attempts/ {
        proxy_pass http://attempts_service:8009/;
    }

    # =========================
    # PROGRESS SERVICE
    # =========================
    location /api/progress/ {
        proxy_pass http://progress_service:8008/;
    }

    # =========================
    # INTEGRATION SERVICE
    # =========================
    location /api/integration/ {
        proxy_pass http://integration_service:8012/;
    }

    location /api/ws {
    rewrite ^/api/ws$ /ws break;

    proxy_pass http://task_manager:8004;

    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";

    proxy_set_header Host $host;
    }

}