version: "3.9"

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - mentor-net

  websocket_service:
    build: 
      context: ./websocket_service
    container_name: websocket_service
    ports:
      - "8000:8000"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis
      - user_service
    networks:
      - mentor-net

  mentor_service:
    build:
      context: ./mentor_service
    container_name: mentor_service
    ports:
      - "8001:8001"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis
    networks:
      - mentor-net

  db:
    image: postgres:15
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users_db
    ports:
      - "5432:5432"
    networks:
      - mentor-net

  user_service:
    build:
      context: ./user_service
    container_name: user_service
    ports:
      - "8002:8002"
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/users_db
      SECRET_KEY: supersecret
    depends_on:
      - db
    networks:
      - mentor-net
    volumes:
      - pgdata:/var/lib/postgresql/data

  sandbox_service:
    build:
      context: ./sandbox_service
    container_name: sandbox_service
    ports:
      - "8003:8003"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis
    networks:
      - mentor-net

networks:
  mentor-net:
    driver: bridge

volumes:
  pgdata: