version: "3.9"

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - mentor-net

  db:
    image: postgres:15
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users_db
    ports:
      - "5432:5432"
    volumes:
    - ./postgres-init:/docker-entrypoint-initdb.d
    networks:
      - mentor-net

  user_service:
    build:
      context: ./user_service
    container_name: user_service
    ports:
      - "8002:8002"
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/users_db
      SECRET_KEY: supersecret
    depends_on:
      - db
    networks:
      - mentor-net
    volumes:
      - pgdata:/var/lib/postgresql/data


  learning_service:
    build: ./learning_service
    container_name: learning_service
    environment:
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=supersecret
    ports:
      - "8001:8001"
    depends_on:
      - redis
      - user_service
    networks:
        - mentor-net
    volumes:
      - ./logs/learning_service:/app/logs
  
  scaffolding_service:
    build: ./scaffolding_service
    container_name: scaffolding_service
    environment:
      - REDIS_URL=redis://redis:6379
    ports:
      - "8003:8003"
    depends_on:
      - redis
      - learning_service
      - user_service
    networks:
        - mentor-net

  task_manager:
    build: 
      context: ./task_manager
    container_name: task_manager
    ports:
      - "8004:8004"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SECRET_KEY: supersecret
    depends_on:
      - redis
      - user_service
    networks:
      - mentor-net
    volumes:
      - ./logs/task_manager:/app/logs

  sandbox_service:
    build:
      context: ./sandbox_service
    container_name: sandbox_service
    ports:
      - "8005:8005"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis
    networks:
      - mentor-net

  mentor_service:
    build:
      context: ./mentor_service
    container_name: mentor_service
    gpus: all
    ports:
      - "8006:8006"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
      MENTOR_MODEL_ID: disemenova/qwen2.5-7b-ai-mentor
      MENTOR_MAX_SEQ_LENGTH: 1024
      MENTOR_MAX_NEW_TOKENS: 256
      MENTOR_TEMPERATURE: 0.7
      MENTOR_REPETITION_PENALTY: 1.1
      MENTOR_LOAD_IN_4BIT: "true"
      MENTOR_EAGER_LOAD: "true"
    depends_on:
      - redis
    networks:
      - mentor-net

  analitics_service:
    build:
      context: ./analitics_service
    container_name: analitics_service
    gpus: all
    ports:
      - "8007:8007"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
    depends_on:
      - redis
    networks:
      - mentor-net
    volumes:
      - ./logs/analitics_service:/app/logs

  progress_service:
    build:
      context: ./progress_service
    container_name: progress_service
    ports:
      - "8008:8008"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis
    networks:
      - mentor-net
    volumes:
      - ./logs/progress_service:/app/logs

  attempts_service:
    build:
      context: ./attempts_service
    container_name: attempts_service
    ports:
      - "8009:8009"
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/attempts
      SECRET_KEY: supersecret
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - db
      - redis
    networks:
      - mentor-net
    volumes:
      - pgdata:/var/lib/postgresql/data

  integration_service:
    build:
      context: ./integration_service
    container_name: integration_service
    ports:
      - "8012:8012"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis
    networks:
      - mentor-net

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ../frontend/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/dist:/usr/share/nginx/html
    depends_on:
      - user_service
      - learning_service
      - attempts_service
      - progress_service
      - integration_service
      - scaffolding_service
    networks:
      - mentor-net



networks:
  mentor-net:
    driver: bridge

volumes:
  pgdata: