version: "3.9"

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - mentor-net

  websocket_service:
    build: 
      context: ./websocket_service
    container_name: websocket_service
    ports:
      - "8000:8000"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis
    networks:
      - mentor-net

networks:
  mentor-net:
    driver: bridge
  default:
    external: false
    name: mentor-net
